#!/usr/bin/env fish

function set_emacs_colors -d 'Set color scheme according to Emacs faces.'
    set -gx fish_color_autosuggestion    '#2aa1ae'
    set -gx fish_color_cancel    '#e0211d'
    set -gx fish_color_command   --bold '#4f97d7'
    set -gx fish_color_comment    '#2aa1ae'
    set -gx fish_color_cwd    '#b2b2b2'
    set -gx fish_color_cwd_root    '#b2b2b2'
    set -gx fish_color_end    '#b2b2b2'
    set -gx fish_color_error    '#e0211d'
    set -gx fish_color_escape    '#b2b2b2'
    set -gx fish_color_history_current    '#b2b2b2'
    set -gx fish_color_host    '#b2b2b2'
    set -gx fish_color_host_remote    '#b2b2b2'
    set -gx fish_color_match    '#b2b2b2'
    set -gx fish_color_normal    '#b2b2b2'
    set -gx fish_color_operator   --bold '#bc6ec5'
    set -gx fish_color_param    '#b2b2b2'
    set -gx fish_color_quote    '#2d9574'
    set -gx fish_color_redirection   --bold '#bc6ec5'
    set -gx fish_color_search_match    '#b2b2b2'
    set -gx fish_color_selection    '#b2b2b2'
    set -gx fish_color_status    '#b2b2b2'
    set -gx fish_color_user    '#b2b2b2'
end
